name: test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-api:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup-go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"

      - name: test
        run: >
          mkdir -p ui/dist
          && echo -e "User-agent: *\nDisallow: /api" > ui/dist/robots.txt
          && go test -v -count=1 -race ./...

      - name: lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.4.0

  test-ui:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./ui

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup-pnpm
        uses: pnpm/action-setup@v4
        with:
          version: '10'

      - uses: actions/setup-node@v4
        with:
          node-version: '22.18'
          cache: 'pnpm'
          cache-dependency-path: ui/pnpm-lock.yaml

      - name: install
        run: pnpm install

      - name: test
        run: pnpm type-check

      - name: lint
        run: pnpm lint
